### ISSUE TITLE
Container get() doesn't support auto-wiring

### ISSUE THREAD

**Issue by baukevdw** [neat-php/service#3]
Container->get() and Container->getOrCreate() should be merged to support auto-wiring in a PSR compliant manner.

**Comment by annavanbiemen** [comment]
Container->get() seems PSR compliant in that it throws a NotFoundException when the requested service wasn't defined (either as instance or factory). When it IS defines as a factory that depends on auto wiring, it is in fact defined and should be created. Using auto wiring doesn't cause PSR compliancy issues in my opinion.
